# Generated by Django 3.1.2 on 2020-10-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capilarte1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aroma',
            name='descripcion',
            field=models.TextField(default='Descripción del aroma', max_length=2000),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_prod',
            field=models.TextField(default='Descripción del producto', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aroma',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
